# Generated by Django 4.2.18 on 2025-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
