# Generated by Django 4.2.18 on 2025-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reddit_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
