# Generated by Django 4.2.18 on 2025-02-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0005_customuser_reddit_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reddit_access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reddit_refresh_token',
        ),
    ]
