# Generated by Django 4.2.18 on 2025-02-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0006_remove_customuser_reddit_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
