# Generated by Django 4.2.18 on 2025-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0009_linkedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaccount',
            name='access_token_secret',
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='platform',
            field=models.CharField(choices=[('mastodon', 'Mastodon')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TwitterRequestTracker',
        ),
    ]
